/**
 * API 에러 코드 상수 — API_SCHEME.md §9
 */

// 공통
export const ERROR_CODES = {
  // 공통
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // 보고서
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_ALREADY_EXISTS: 'REPORT_ALREADY_EXISTS',
  INVALID_REPORT_DATE: 'INVALID_REPORT_DATE',
  REPORT_ALREADY_SUBMITTED: 'REPORT_ALREADY_SUBMITTED',

  // 방문 기록
  VISIT_RECORD_NOT_FOUND: 'VISIT_RECORD_NOT_FOUND',
  MINIMUM_VISIT_RECORD: 'MINIMUM_VISIT_RECORD',

  // Problem / Plan
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  INVALID_NOTE_TYPE: 'INVALID_NOTE_TYPE',

  // 댓글
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',

  // 고객 마스터
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',

  // 영업 사원 마스터
  SALESPERSON_NOT_FOUND: 'SALESPERSON_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  SELF_MANAGER_REFERENCE: 'SELF_MANAGER_REFERENCE',
  CIRCULAR_MANAGER_REFERENCE: 'CIRCULAR_MANAGER_REFERENCE',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
